CREATE DATABASE IF NOT EXISTS fwsp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fwsp;
CREATE TABLE IF NOT EXISTS location_masterlist (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    region VARCHAR(120) NOT NULL,
    branch VARCHAR(160) NOT NULL,
    province VARCHAR(160) NOT NULL,
    facility_name VARCHAR(180) NOT NULL,
    UNIQUE KEY location_master_unique (region, branch, province, facility_name)
);
CREATE TABLE IF NOT EXISTS province_offices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    branch_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    UNIQUE KEY province_branch_unique (branch_id, name),
    FOREIGN KEY (branch_id) REFERENCES branch_offices(id)
);
ALTER TABLE warehouse_offices ADD COLUMN IF NOT EXISTS province_id BIGINT UNSIGNED NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS province_id BIGINT UNSIGNED NULL;
CREATE INDEX IF NOT EXISTS warehouse_branch_idx ON warehouse_offices (branch_id);
ALTER TABLE warehouse_offices DROP INDEX IF EXISTS warehouse_branch_unique;
TRUNCATE TABLE location_masterlist;
INSERT IGNORE INTO location_masterlist (region, branch, province, facility_name) VALUES
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Eastern Pangasinan Branch Office'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Binalonan GID'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Binalonan DM'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Binalonan Triplex'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'LSU Type, Batch Recirculating Dryer'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Maruyama, Batch Recirculating Dryer'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Rosales I'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Rosales II'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Naric'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Agricom, Batch Recirculating Dryer'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Satake Ricemill'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'Asingan FLGC'),
('Region I', 'Eastern Pangasinan Branch Office', 'Eastern Pangasinan', 'San Quintuin FLGC'),
('Region I', 'Eastern Pangasinan Branch Office', 'Western Pangasinan', 'Mangatarem GID I'),
('Region I', 'Eastern Pangasinan Branch Office', 'Western Pangasinan', 'Mangatarem GID II'),
('Region I', 'Eastern Pangasinan Branch Office', 'Western Pangasinan', 'Alaminos GID'),
('Region I', 'Eastern Pangasinan Branch Office', 'Western Pangasinan', 'Unique 1 Warehouse (Leased)'),
('Region I', 'Eastern Pangasinan Branch Office', 'Western Pangasinan', 'Unique 2 Warehouse (Leased)'),
('Region I', 'Eastern Pangasinan Branch Office', 'Western Pangasinan', 'Corporate Farming-RPS 1 (Free rent)'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Norte', 'Ilocos Norte Branch Office'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Norte', 'Laoag GID'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Norte', 'Dingras Multi-Purpose'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Norte', 'Dingras Duplex'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Norte', 'Agricom LSU-Type Recirculating Dryer'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Norte', 'AMCC LSU Recirculating Dryer'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Norte', 'Satake Ricemill'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Sur', 'Ilocos Sur Office'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Sur', 'Bantay GID I'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Sur', 'Bantay GID II'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Sur', 'Maruyama, Batch Recirculating Dryer'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Sur', 'FLGC III'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Sur', 'Tomato Paste Plant Warehouse'),
('Region I', 'Ilocos Norte Branch Office', 'Ilocos Sur', 'Candon City Warehouse'),
('Region I', 'Ilocos Norte Branch Office', 'Abra', 'Abra Office'),
('Region I', 'Ilocos Norte Branch Office', 'Abra', 'AHTC Warehouse'),
('Region I', 'Ilocos Norte Branch Office', 'Abra', 'Bangued GID'),
('Region I', 'La Union Branch Office', 'La Union', 'La Union Branch Office'),
('Region I', 'La Union Branch Office', 'La Union', 'San Juan GID Warehouse 1'),
('Region I', 'La Union Branch Office', 'La Union', 'San Juan GID Warehouse 2'),
('Region I', 'La Union Branch Office', 'Benguet', 'Loakan Staffhouse & Training Center'),
('Region I', 'La Union Branch Office', 'Benguet', 'Loakan GID Warehouse'),
('Region I', 'NFA Regional Office', 'La Union', 'NFA Regional Office 1'),
('Region II', 'NFA Region 2', 'Isabela', 'NFA Regional Office 2'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Cagayan Branch Office'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Isabela Branch Office'),
('Region II', 'Nueva Vizcaya Branch Office', 'Nueva Vizcaya', 'Nueva Vizcaya Branch Office'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Carig GID I'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Carig GID II'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Carig Triplex'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Gonzaga GID III'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Lasam GID III'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Matucay GID I Duplex'),
('Region II', 'Cagayan Branch Office', 'Apayao', 'Luna GID II Duplex'),
('Region II', 'Cagayan Branch Office', 'Kalinga', 'Rizal FLGC'),
('Region II', 'Cagayan Branch Office', 'Kalinga', 'Tabuk GID Duplex'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Alicia FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Burgos FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Cabagan FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Cabatuan FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Cauayan FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Cordon FSW'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Delfin Albano MLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Gamu DUPLEX'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Luna FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Mallig FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Echague NPGC Triplex-GREEN'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Echague NPGC Trplex-WHITE'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Palanan GID'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Quezon FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Ramon FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Roxas GID I'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Roxas GID II'),
('Region II', 'Isabela Branch Office', 'Isabela', 'San Isidro FLGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'San Manuel GID'),
('Region II', 'Isabela Branch Office', 'Isabela', 'San Mateo GID DUPLEX'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Tumauini GID'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Santiago GID'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Santiago TRIPLEX'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Echague NPGC Corn Center'),
('Region II', 'Nueva Vizcaya Branch Office', 'Nueva Vizcaya', 'Bayombong GID I'),
('Region II', 'Nueva Vizcaya Branch Office', 'Nueva Vizcaya', 'Bayombong GID II'),
('Region II', 'Nueva Vizcaya Branch Office', 'Nueva Vizcaya', 'Bayombong DUPLEX'),
('Region II', 'Nueva Vizcaya Branch Office', 'Nueva Vizcaya', 'Bagabag FLGC'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Cabarroguis GID I'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Cabarroguis GID II'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Ricemill House'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Diffun FLGC'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Saguday FLGC'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Maddela FLGC'),
('Region II', 'Nueva Vizcaya Branch Office', 'Ifugao', 'Lagawe GID'),
('Region II', 'Nueva Vizcaya Branch Office', 'Ifugao', 'Alfonso Lista FLGC'),
('Region II', 'Nueva Vizcaya Branch Office', 'Mountain Province', 'Bontoc GID'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Aparri Buying Station'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Peñablanca Buying Station'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Solana I Buying Station'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Solana II Buying Station'),
('Region II', 'Cagayan Branch Office', 'Kalinga', 'Rizal Buying Station'),
('Region II', 'Cagayan Branch Office', 'Apayao', 'Conner Buying Station'),
('Region II', 'Cagayan Branch Office', 'Apayao', 'Flora Buying Station'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Agricomp Dryer');
INSERT IGNORE INTO location_masterlist (region, branch, province, facility_name) VALUES
('Region II', 'Cagayan Branch Office', 'Cagayan', 'Shin Hueng Dryer'),
('Region II', 'Cagayan Branch Office', 'Kalinga', 'Shin Hueng Dryer'),
('Region II', 'Cagayan Branch Office', 'Kalinga', 'Padiscor Dryer'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Cimbria Dryer'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Agricomp Dryer'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Shin Hueng Dryer'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Mechapil Dryer'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Padiscor Dryer'),
('Region II', 'Nueva Vizcaya Branch Office', 'Nueva Vizcaya', 'Agricomp Dryer'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Agricomp Dryer'),
('Region II', 'Nueva Vizcaya Branch Office', 'Quirino', 'Shin Hueng Dryer'),
('Region II', 'Nueva Vizcaya Branch Office', 'Ifugao', 'Shin Hueng Dryer'),
('Region II', 'Cagayan Branch Office', 'Kalinga', 'Satake Ricemill Tabuk'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Satake Ricemill Santiago'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Satake Ricemill NPGC'),
('Region II', 'Isabela Branch Office', 'Isabela', 'Satake Ricemill Roxas'),
('Region II', 'Isabela Branch Office', 'Isabela', 'NPGC Echague Truckscale'),
('Region II', 'Isabela Branch Office', 'Isabela', 'NFA Santiago Truckscale'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'NFA Tuguegarao Truckscale'),
('Region II', 'Cagayan Branch Office', 'Cagayan', 'NFA Allacapan Truckscale'),
('Region II', 'Nueva Vizcaya Branch Office', 'Nueva Vizcaya', 'MGC Bayombong Truckscale'),
('Region III', 'Regional Office IIII', 'Nueva Ecija', 'Central Luzon Regional Office'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Tarlac Branch Office'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Aguso Warehouse 1'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Aguso Warehouse 2'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Aguso Warehouse 3'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Aguso Warehouse 3-Annex'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'New Construction of Modernized Whse'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Aguso Warehouse 5'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'La Paz Office'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'La Paz GID I'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'La Paz GID II'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'La Paz GID III'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Concepcion Office'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Concepcion GID'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'ShinHeung Recirculating Grain Dryer'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Talimundok FLGC'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Camiling Productivity Center'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'Sta. Ines Productivity Center'),
('Region III', 'Tarlac Branch Office', 'Tarlac', 'San Manuel Warehouse'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'Bulacan Branch Office'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'Balagtas 1'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'Balagtas 2'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'Balagtas 3'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'San Ildefonso 1'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'San Ildefonso 2'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'Sta Rita 1A'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'Sta Rita 2A'),
('Region III', 'Bulacan Branch Office', 'Bulacan', 'Tikay'),
('Region III', 'Pampanga Branch Office', 'Bataan', 'Balanga 1'),
('Region III', 'Pampanga Branch Office', 'Bataan', 'Balanga 2'),
('Region III', 'Pampanga Branch Office', 'Bataan', 'Farm Level Grain Center III - Dinalupihan'),
('Region III', 'Pampanga Branch Office', 'Bataan', 'Bataan Satellite Office'),
('Region III', 'Pampanga Branch Office', 'Pampanga', 'Pampanga Branch Office'),
('Region III', 'Pampanga Branch Office', 'Pampanga', 'Sindalan 1'),
('Region III', 'Pampanga Branch Office', 'Pampanga', 'Sindalan 2'),
('Region III', 'Pampanga Branch Office', 'Pampanga', 'TSB Warehouse'),
('Region III', 'Pampanga Branch Office', 'Pampanga', 'Farm Level Grain Center III - San Luis'),
('Region III', 'Pampanga Branch Office', 'Zambales', 'Castillejos'),
('Region III', 'Pampanga Branch Office', 'Zambales', 'Zambales Satellite Office'),
('Region III', 'Pampanga Branch Office', 'Zambales', 'Mango Terminal'),
('Region III', 'Pampanga Branch Office', 'Zambales', 'Iba'),
('Region III', 'Pampanga Branch Office', 'Zambales', 'Maruyama YC-100'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Nueva Ecija Branch Office'),
('Region III', 'Nueva Ecija Branch Office', 'Aurora', 'Baler GID Main & Annex A'),
('Region III', 'Nueva Ecija Branch Office', 'Aurora', 'Baler GID Annex B'),
('Region III', 'Nueva Ecija Branch Office', 'Aurora', 'Bartolome Warehouse'),
('Region III', 'Nueva Ecija Branch Office', 'Aurora', 'Casiguran Warehouse'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Cabanatuan Warehouse 1'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Cabanatuan Warehouse 2'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Cabanatuan Warehouse 3'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Cabanatuan Warehouse 11 (Duplex)'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Cabanatuan Warehouse 12 (Triplex)'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Cabanatuan Warehouse 13'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Aliaga Food Center'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Bongabon Food Center'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Gapan Food Center'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Guimba Warehouse 1 (Duplex)'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Guimba Warehouse 2'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Guimba Drier House'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Muñoz Warehouse 1'),
('Region III', 'Nueva Ecija Branch Office', 'Nueva Ecija', 'Valle FLGC'),
('Region IV', 'Oriental Mindoro Branch Office', 'Oriental Mindoro', 'Oriental Mindoro Branch Office'),
('Region IV', 'Oriental Mindoro Branch Office', 'Oriental Mindoro', 'GID Calapan Warehouse'),
('Region IV', 'Oriental Mindoro Branch Office', 'Oriental Mindoro', 'GID Naujan Warehouse'),
('Region IV', 'Oriental Mindoro Branch Office', 'Oriental Mindoro', 'GID-I Pinamalayan Warehouse'),
('Region IV', 'Oriental Mindoro Branch Office', 'Oriental Mindoro', 'GID-II Pinamalayan Warehouse'),
('Region IV', 'Oriental Mindoro Branch Office', 'Oriental Mindoro', 'RGC Warehouse'),
('Region IV', 'Oriental Mindoro Branch Office', 'Oriental Mindoro', 'GID Roxas Duplex Warehouse'),
('Region IV', 'Quezon Branch Office', 'Quezon', 'Quezon Branch Office'),
('Region IV', 'Quezon Branch Office', 'Quezon', 'GID Lucena'),
('Region IV', 'Quezon Branch Office', 'Quezon', 'ONG Warehouse'),
('Region IV', 'Quezon Branch Office', 'Quezon', 'FLGC'),
('Region IV', 'Laguna Branch Office', 'Laguna', 'GID 2'),
('Region IV', 'Laguna Branch Office', 'Laguna', 'GID 1'),
('Region IV', 'Laguna Branch Office', 'Laguna', 'GID Infanta'),
('Region IV', 'Laguna Branch Office', 'Laguna', 'FLGC III'),
('Region IV', 'Laguna Branch Office', 'Laguna', 'Laguna Branch Office'),
('Region IV', 'Regional Office IV', 'Batangas', 'NFA Regional Office IV'),
('Region IV', 'Batangas Branch Office', 'Batangas', 'Batangas Branch Office');
INSERT IGNORE INTO location_masterlist (region, branch, province, facility_name) VALUES
('Region IV', 'Batangas Branch Office', 'Batangas', 'GID II Batangas'),
('Region IV', 'Batangas Branch Office', 'Batangas', 'GID IIA Batangas'),
('Region IV', 'Batangas Branch Office', 'Batangas', 'GID Romblon'),
('Region IV', 'Batangas Branch Office', 'Batangas', 'Suntons Warehouse (Leased Warehouse)'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Occidental Mindoro Branch Office'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 1'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 2'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 3'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 4'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 5'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 6'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'NAWACO 1'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'NAWACO 2'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 7'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID 8'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID Sablayan'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'GID Duplex'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Mamburao Office'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Jafpy Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Pacunla 2A Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Pacunla 2B Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Sebastian Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Almuete Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Magsaysay Orig Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Magsaysay First Christian MPC'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Pablo Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Salvacion Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'PAKIKIBAGAI Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Miller Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'AMMAN Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'MAMAMUCO Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'Manayan Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'New Life Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'ABIA Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'LIMFCO Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'SACAMUCO Warehouse'),
('Region IV', 'Occidental Mindoro Branch Office', 'Occidental Mindoro', 'New Pajayon Warehouse'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'Palawan (New) Branch Office'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'Palawan (Old) Branch Office'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'NFA Owned'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'GID 01 Warehouse'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'GID 02 Warehouse'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'GID 02 Warehouse- Annex'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'GID 03 Warehouse'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'PARCOFED 1 Warehouse'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'PARCOFED 2 Warehouse'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'LGU-RAC Rizal Buying Station'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'SAMAGMA Warehouse'),
('Region IV', 'Palawan Branch Office', 'Palawan', 'MCFA PRC 2 Warehouse'),
('Region V', 'Regional Office', 'Albay', 'NFA Regional Office No. V'),
('Region V', 'Albay Branch Office', 'Albay', 'Albay Branch Office'),
('Region V', 'Albay Branch Office', 'Albay', 'Legazpi GID Warehouse'),
('Region V', 'Albay Branch Office', 'Albay', 'Ligao Warehouse'),
('Region V', 'Albay Branch Office', 'Albay', 'Tabaco Abacorp Warehouse'),
('Region V', 'Albay Branch Office', 'Albay', 'Tabaco GID Warehouse'),
('Region V', 'Albay Branch Office', 'Albay', 'Libon Warehouse'),
('Region V', 'Albay Branch Office', 'Albay', 'GT 345XL Batch Recirculating Dryer'),
('Region V', 'Albay Branch Office', 'Albay', 'Catanduanes Field Office'),
('Region V', 'Albay Branch Office', 'Albay', 'Virac GID II Warehouse'),
('Region V', 'Albay Branch Office', 'Albay', 'Kolbi Ricemill (Diesel Engine)'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'Camarines Sur Branch Office'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'GID 1 Warehouse Pili'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'GID 2 Warehouse Pili'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'Buivanggo Multi-pass Ricemill'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'Agricom Batch Recirculating Dryer'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'GID Libmanan Warehouse'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'Camarines Norte Field Office'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'GID 1 Daet Warehouse'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'GID 2 Daet Warehouse'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'Kolbi Ricemill (Electric)'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'DA Flatbed Dryer'),
('Region V', 'Camarines Sur Branch Office', 'Camarines Sur', 'Flatbed Dryer'),
('Region V', 'Sorsogon Branch Office', 'Sorsogon', 'Sorsogon Branch Office'),
('Region V', 'Sorsogon Branch Office', 'Sorsogon', 'GID 1 Warehouse Sorsogon'),
('Region V', 'Sorsogon Branch Office', 'Sorsogon', 'GID 2 Warehouse Sorsogon'),
('Region V', 'Sorsogon Branch Office', 'Sorsogon', 'GID 3 Warehouse Sorsogon'),
('Region V', 'Sorsogon Branch Office', 'Sorsogon', 'Shin Heung Batch Recirculating Dryer'),
('Region V', 'Sorsogon Branch Office', 'Sorsogon', 'Megasun Batch Recirculating Dryer'),
('Region V', 'Sorsogon Branch Office', 'Masbate', 'Masbate Field Office'),
('Region V', 'Sorsogon Branch Office', 'Masbate', 'GID Warehouse Masbate'),
('Region V', 'Sorsogon Branch Office', 'Masbate', 'GID 1 Warehouse Masbate'),
('Region V', 'Sorsogon Branch Office', 'Masbate', 'Kolbi Ricemill (Electric)'),
('Region V', 'Sorsogon Branch Office', 'Masbate', 'Flatbed Dryer'),
('Region VI', 'Negros Occidental Branch', 'Negros Occ', 'GID Warehouse'),
('Region VI', 'Negros Occidental Branch', 'Negros Occ', 'Negros Occidental Branch Office'),
('Region VI', 'Negros Occidental Branch', 'Negros Occ', 'Malaluan Warehouse A (Leased)'),
('Region VI', 'Negros Occidental Branch', 'Negros Occ', 'Malaluan Warehouse B (Leased)'),
('Region VI', 'Capiz Branch', 'Capiz', 'Sigma Grains Center'),
('Region VI', 'Capiz Branch', 'Capiz', 'Bolo Grains Center'),
('Region VI', 'Capiz Branch', 'Capiz', 'Dumalag Grains Center'),
('Region VI', 'Capiz Branch', 'Aklan', 'Aklan Grains Center'),
('Region VI', 'Capiz Branch', 'Capiz', 'Maruyama Recirculating Dryer'),
('Region VI', 'Capiz Branch', 'Capiz', 'Satake Ricemill'),
('Region VI', 'Iloilo Branch', 'Antique', 'GID Camp Fullon 1'),
('Region VI', 'Iloilo Branch', 'Antique', 'GID Camp Fullon 3'),
('Region VI', 'Iloilo Branch', 'Antique', 'GID Culasi'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Jaro Triplex Warehouse'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Kabsaka Triplex Warehouse'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Dumangas Grains Center'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Pototan Grains Center');
INSERT IGNORE INTO location_masterlist (region, branch, province, facility_name) VALUES
('Region VI', 'Iloilo Branch', 'Iloilo', 'San Dionisio Warehouse'),
('Region VI', 'Iloilo Branch', 'Guimaras', 'Jordan Warehouse'),
('Region VI', 'Iloilo Branch', 'Guimaras', 'Millan JICA'),
('Region VI', 'Iloilo Branch', 'Guimaras', 'Suclaran JICA'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Shin Heung Mechanical Dryer'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Maruyama Recirculating Dryer'),
('Region VI', 'Iloilo Branch', 'Antique', 'Agricum LSU Type-Circulating Dryer'),
('Region VI', 'Iloilo Branch', 'Antique', 'Agricum Biomass'),
('Region VI', 'Iloilo Branch', 'Antique', 'Shun Kuan EC50 Recirculating Dryer'),
('Region VI', 'Iloilo Branch', 'Antique', 'Shin Heung Mechanical  Dryer'),
('Region VI', 'Iloilo Branch', 'Antique', 'Antique Satake Ricemill'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Dumangas Satake Ricemill'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Jaro Satake Ricemill'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Jaro MAFIM'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Dumangas MAFIM'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Dueñas MAFIM'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Shin Heung'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Modified Flatbed Dryer (TWIN)'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Modified Flatbed Dryer'),
('Region VI', 'Iloilo Branch', 'Iloilo', 'Iloilo Branch Office'),
('Region VI', 'Regional Office', 'Iloilo', 'Western Visayas Regional Office'),
('Region VI', 'Capiz Branch', 'Capiz', 'Satake Batch Recirculating Dryer'),
('Region VI', 'Capiz Branch', 'Aklan', 'Shin Heung Mechanical  Dryer'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'GID I / Warehouse-19'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'GID II / Bogo Unit Warehouse (proposed for major repair)'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'GID III / Tudela Unit Warehouse (proposed for major repair)'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'GID IV / Badian Unit Warehouse (under MAFIM repairs)'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'GID V / Sta Fe Unit Warehouse (under MAFIM repairs)'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'Warehouse # 46 (under MAFIM repairs)'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'GID VIII Warehouse (under MAFIM repairs)'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'Centennial Warehouse (under usufruct agreement w/ FTI)'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'Warehouse # 9'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'Cebu Branch Office'),
('Region VII', 'Cebu Branch Office', 'Cebu', 'Asuki Truckscale'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'Bohol Branch Office'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'GID Warehouse (w/ extension)'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'FLGC III Warehouse'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'FSC Warehouse'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'Anihan Portable Recirculating Dryer'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'Green Mac Batch Recirculating Dryer'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'Shin Heung Batch Recirculating Dryer'),
('Region VII', 'Bohol Branch Office', 'Bohol', 'Satake Rice Mill'),
('Region VII', 'Negros Oriental Branch Office', 'Negros Oriental', 'Negros Oriental Branch Office'),
('Region VII', 'Negros Oriental Branch Office', 'Negros Oriental', 'GID I Dumaguete'),
('Region VII', 'Negros Oriental Branch Office', 'Negros Oriental', 'Daichi Ricemill'),
('Region VII', 'Negros Oriental Branch Office', 'Negros Oriental', 'GID II Guihulngan'),
('Region VII', 'Negros Oriental Branch Office', 'Siquijor', 'GID Siquijor'),
('Region VIII', 'Regional Office', 'Leyte', 'Regional Office'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Leyte Branch Office'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'GID Port Area Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'GID Alangalang Warehouse I'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'GID Alangalang Warehouse II'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Alangalang Warehouse-Millhouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Alangalang Maruyama Dryer'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Modernized Warehouse (on-going construction under MAFIM Program)'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Alangalang Warehouse- Ricemill'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Ricemill for Modernized Warehouse (on-going construction under MAFIM Program)'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Dryers Modernized warehouse (on-going construction under MAFIM Program)'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'GID Cogon Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'GID San Pablo Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'GID Baybay Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'NFA Naval satellite Office'),
('Region VIII', 'Leyte Branch Office', 'Biliran', 'GID Naval Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Biliran', 'Naval PHF Shedhouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'NFA Naval Mechanical Dryers'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'JICA Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'NFA Maasin Satellite Office'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'GID Maasin Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'FLGC Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'FLGC LSU Mechanical Dryer'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'JK  Leased Warehouse'),
('Region VIII', 'Leyte Branch Office', 'Leyte', 'Delta Leased Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'Leased Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'Northern Samar Branch Office'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Bobon Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Rawis Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'NFA-Owned Duplex Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Catubig Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'Maruyama Dryer'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Guiuan Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Borongan Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'Borongan Satellite Office'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Oras Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'Modernized Warehouse (on-going construction under MAFIM Program)'),
('Region VIII', 'Samar Branch Office', 'Samar', 'Catbalogan Satellite Office'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Catbalogan Warehouse'),
('Region VIII', 'Samar Branch Office', 'Samar', 'Catbalogan Dryer house'),
('Region VIII', 'Samar Branch Office', 'Samar', 'GID Calbayog Warehouse'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'Zamboanga City Branch Office'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'New GID WHSE'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'Warehouse A/B (Lease Warehouse)'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'GID/FOREMOST WHSE C/D'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'Truck Scale'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'GID Taway WHSE'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'GID Guilawa WHSE'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'Dryer House'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'GTM Leased Warehouse'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'FLGC Siay WHSE'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'Bangco Titay WHSE (For Repair/Improvement)'),
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'Taway, Ipil Unit Office(To be demolish)');
INSERT IGNORE INTO location_masterlist (region, branch, province, facility_name) VALUES
('Region IX', 'Zamboanga Branch Office', 'Zamboanga Del Sur', 'Regional Office'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Zamboanga del Sur Branch Office'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Tiguma A WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Tiguma B WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Tiguma C WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Molave Satelitte Branch Office'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Culo A WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Culo B WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Culo C WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Dumingag FLGC WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Norte', 'Dipolog Satelitte Branch Office'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Norte', 'GID I Dipolog WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Norte', 'GID II Dipolog WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Norte', 'Dryer House'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Osmena FSC WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Norte', 'Liloy LFSC WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Norte', 'GID Siocon WHSE'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'San Miguel FSW'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Truck Scale'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Norte', 'Truck Scale'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Villoria Rice and Corn Mill'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'Fernandez Rice Mill & Buying Station'),
('Region IX', 'Zamboanga del Sur Branch Office', 'Zamboanga Del Sur', 'C & A Rice Mill'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'NFA Bukidnon Branch Office'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Aglayan Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Valencia Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Musuan Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Maramag Main Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Maramag Annex Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Kalilangan Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Wao Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'GID Wao INF Warehouse'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'Mechaphil Batch Recirculating Mech. Grain Dryer (3 Units)'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'Alheed Batch Recirculating Mech. Grain Dryer (2 Units)'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'Shin Neung Batch Recirculating Mech. Grain Dryer (1 Unit)'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'Alheed Batch Recirculating Mech. Grain Dryer (1 Unit)'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'Greenmac Batch Recirculating Mech. Grain Dryer (3 Units)'),
('Region X', 'Bukidnon Branch Office', 'Bukidnon', 'Mechaphil Batch Recirculating Mech. Grain Dryer (2 Units)'),
('Region X', 'Misamis Oriental Branch Office', 'Cagayan De Oro', 'NFA Misamis Oriental Branch Office'),
('Region X', 'Misamis Oriental Branch Office', 'Cagayan De Oro', 'GID 1, Patag Warehouse'),
('Region X', 'Misamis Oriental Branch Office', 'Cagayan De Oro', 'GID 2, Baloy Warehouse'),
('Region X', 'Misamis Oriental Branch Office', 'Cagayan De Oro', 'GID 3, Baloy Warehouse'),
('Region X', 'Misamis Oriental Branch Office', 'Cagayan De Oro', 'GID 4, Baloy Warehouse'),
('Region X', 'Misamis Oriental Branch Office', 'Camiguin', 'NFA Camiguin Sub- Office'),
('Region X', 'Misamis Oriental Branch Office', 'Camiguin', '20TCC Warehouse'),
('Region X', 'Misamis Oriental Branch Office', 'Camiguin', 'FLGC Warehouse'),
('Region X', 'Lanao del Norte Branch Office', 'Lanao Del Norte', 'NFA Lanao del Norte Branch Office'),
('Region X', 'Lanao del Norte Branch Office', 'Lanao Del Norte', 'GID 1 Iligan Warehouse'),
('Region X', 'Lanao del Norte Branch Office', 'Lanao Del Norte', 'Zemic Truckscale 60T'),
('Region X', 'Lanao del Norte Branch Office', 'Lanao Del Norte', 'GID 2 Lala Warehouse'),
('Region X', 'Lanao del Norte Branch Office', 'Lanao Del Norte', 'Suncue Recirculating Mech. Grain Dryer 6TPB'),
('Region X', 'Lanao del Norte Branch Office', 'Lanao Del Norte', 'Hansung Recirculating Mech. Grain Dryer 6TPB'),
('Region X', 'Lanao del Norte Branch Office', 'Lanao Del Norte', 'LSU Agricom Recirculating Mech. Grain Dryer 6TB'),
('Region X', 'Lanao del Norte Branch Office', 'Misamis Occidental', 'GID 1 Ozamis Warehouse'),
('Region X', 'Lanao del Norte Branch Office', 'Misamis Occidental', 'GID 2 Ozamis Warehouse'),
('Region X', 'Lanao del Norte Branch Office', 'Misamis Occidental', 'GID 3 Ozamis Warehouse'),
('Region X', 'Lanao del Norte Branch Office', 'Misamis Occidental', 'Suncue Recirculating Mech. Grain Dryer 6TPB'),
('Region X', 'Lanao del Norte Branch Office', 'Misamis Occidental', 'Mega Sun Recirculating Mech. Grain Dryer 6TPB'),
('Region X', 'Lanao del Norte Branch Office', 'Misamis Occidental', 'Sato Ricemill 150 KG/HR'),
('Region X', 'Lanao del Norte Branch Office', 'Misamis Occidental', 'Zemic Truckscale 60T'),
('Region X', 'Regional Office X', 'Cagayan De Oro, Misamis Oriental', 'Regional Office'),
('Region XI', 'Regional Office XI', 'Davao Del Sur', 'Regional Office XI'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'Davao del Sur Branch Office'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'Santa Ana Office'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'Triplex Warehouse'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'GID Warehouse'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'OLD Warehouse'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'MAFIM Warehouse (on-going construction)'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'Santa Ana Warehouse'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'Satake Rice Mill'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'Dryer House'),
('Region XI', 'Davao Del Sur Branch Office', 'Davao Del Sur', 'Truckscale'),
('Region XI', 'Davao Oriental Branch Office', 'Davao Del Sur', 'Davao Oriental Branch Office'),
('Region XI', 'Davao Oriental Branch Office', 'Davao Del Sur', 'GID 3 warehouse'),
('Region XI', 'Davao Oriental Branch Office', 'Davao Del Sur', 'GID 1 WAREHOUSE'),
('Region XI', 'Davao Oriental Branch Office', 'Davao Del Sur', 'GID 2 WAREHOUSE'),
('Region XI', 'Davao Oriental Branch Office', 'Davao Del Sur', 'GID 7 WAREHOUSE'),
('Region XI', 'Davao Oriental Branch Office', 'Davao Del Sur', 'Baganga Buying Station'),
('Region XI', 'Davao Oriental Branch Office', 'Davao Del Sur', 'LSU TYPE MECH. DRYER WITH DRYER HOUSE'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'Davao del Norte Branch Office'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'GID 1 Warehouse'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'GID 2 Warehouse'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'GID Compostela Warehouse'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'Sto. Tomas Warehouse'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'FLGC Maragusan Warehouse'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'Nabunturan Office'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'MAFIM Warehouse (on-going)'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'Maruyama Mechanical Dryer'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'Shin Heung Mechanical Dryer'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'LSU Mechanical Dryer'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'Toledo Truck Scale'),
('Region XI', 'Davao del Norte', 'Davao Del Norte', 'Weightronix Truck Scale'),
('Region XII', 'South Cotabato', 'South Cotabato', 'FLGC Banga'),
('Region XII', 'South Cotabato', 'South Cotabato', 'GID 3 GENERAL SANTOS CITY'),
('Region XII', 'South Cotabato', 'South Cotabato', 'GID 1 GENERAL SANTOS CITY'),
('Region XII', 'South Cotabato', 'South Cotabato', 'GID 2 GENERAL SANTOS CITY'),
('Region XII', 'South Cotabato', 'South Cotabato', 'GID 4 GENERAL SANTOS CITY'),
('Region XII', 'South Cotabato', 'South Cotabato', 'NFA 1 GENERAL SANTOS CITY'),
('Region XII', 'South Cotabato', 'South Cotabato', 'NFA 2 GENERAL SANTOS CITY'),
('Region XII', 'South Cotabato', 'South Cotabato', 'IBG KORONADAL CITY');
INSERT IGNORE INTO location_masterlist (region, branch, province, facility_name) VALUES
('Region XII', 'South Cotabato', 'South Cotabato', 'NFA 1 KORONADAL CITY'),
('Region XII', 'South Cotabato', 'South Cotabato', 'GID 5 MAITUM'),
('Region XII', 'South Cotabato', 'South Cotabato', 'NABCOR BANGA'),
('Region XII', 'South Cotabato', 'South Cotabato', 'MLGC SURALLAH'),
('Region XII', 'South Cotabato', 'South Cotabato', 'SCBO Koronadal City'),
('Region XII', 'South Cotabato', 'South Cotabato', 'NFA Gen. Santos Main Building'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SKBO ISULAN'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA GID 1 LEBAK'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA GID 2 LEBAK'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA GID TRIPLEX ISULAN, (GID 1, GID 2, GID 3)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SPGC QUINTUPLEX (GID 1)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SPGC QUINTUPLEX (GID 2)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SPGC QUINTUPLEX (GID 3)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SPGC QUINTUPLEX (GID 4)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SPGC QUINTUPLEX (GID 5)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SPGC GID 8'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'NFA SPGC DUPLEX (GID7)'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 1 KIDAPAWAN'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 3 KIDAPAWAN'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 5 KIDAPAWAN'),
('Region XII', 'North Cotabato', 'North Cotabato', 'MILL HOUSE KIDAPAWAN'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 4 M''LANG'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 2 M''LANG'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 6 KABACAN'),
('Region XII', 'North Cotabato', 'North Cotabato', 'NFA OWNED 4 BAGUER'),
('Region XII', 'North Cotabato', 'North Cotabato', 'NFA OWNED 1 KIDAPAWAN'),
('Region XII', 'North Cotabato', 'North Cotabato', 'NFA OWNED 2 M''LANG'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 7 BAGUER'),
('Region XII', 'North Cotabato', 'North Cotabato', 'GID 8 KILADA'),
('Region XII', 'Regional Office XII', 'South Cotabato', 'REGIONAL OFFICE 12 BLDG.'),
('Region XII', 'North Cotabato', 'North Cotabato', 'NORTH COTABATO BRANCH OFFICE'),
('Region XII', 'North Cotabato', 'North Cotabato', 'Mechanical Dryer (SHIN HUENG)'),
('Region XII', 'North Cotabato', 'North Cotabato', 'Mechanical Dryer (MARUYAMA)'),
('Region XII', 'North Cotabato', 'North Cotabato', 'Mechanical Dryer (SUNCUE)'),
('Region XII', 'North Cotabato', 'North Cotabato', 'Mechanical Dryer (PHILMEC)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Mechanical Dryer (SATAKE)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Mechanical Dryer (SUNCUE I)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Mechanical Dryer (LSU-AGRICOM)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Mechanical Dryer (SHIN HUENG)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Mechanical Dryer (GREENMAC)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Mechanical Dryer (SUNCUE)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Ricemill (BUHLER MIAG Multi-pass)'),
('Region XII', 'North Cotabato', 'North Cotabato', 'Ricemill (SATAKE Multi-pass)'),
('Region XII', 'South Cotabato', 'South Cotabato', 'Truck Scale (Mettler Toledo)'),
('Region XII', 'South Cotabato', 'South Cotabato', 'Truck Scale (Weightronix)'),
('Region XII', 'North Cotabato', 'North Cotabato', 'Truck Scale (Mettler Toledo)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Truck Scale (Mettler Toledo)'),
('Region XII', 'Sultan Kudarat', 'Sultan Kudarat', 'Truck Scale (Weightronix)'),
('NCR', 'Central District', 'Metro Manila', 'MFC #1'),
('NCR', 'Central District', 'Metro Manila', 'MFC #2'),
('NCR', 'Central District', 'Metro Manila', 'MFC #3'),
('NCR', 'Central District', 'Metro Manila', 'MFC #4'),
('NCR', 'Central District', 'Metro Manila', 'MFC #5'),
('NCR', 'Central District', 'Metro Manila', 'MFC #7'),
('NCR', 'Central District', 'Metro Manila', 'Minprocor'),
('NCR', 'Central District', 'Batanes', 'Basco Warehouse'),
('NCR', 'East District', 'Cavite', 'General Trias A'),
('NCR', 'East District', 'Cavite', 'General Trias B'),
('NCR', 'East District', 'Rizal', 'Antipolo Warehouse 1'),
('NCR', 'East District', 'Rizal', 'Antipolo Warehouse 2'),
('NCR', 'East District', 'Metro Manila', 'Marikina Warehouse'),
('NCR', 'Regional Office NCR', 'Metro Manila', 'NCR Regional Office'),
('NCR', 'Central District', 'Valenzuela', 'MFC Office'),
('NCR', 'East District', 'Antipolo, Rizal', 'East District Branch Office'),
('NCR', 'Central District', 'Batanes', 'Batanes Unit Office'),
('NCR', 'East District', 'Cavite', 'Cavite Office'),
('NCR', 'East District', 'Marikina', 'Marikina Office'),
('NCR', 'East District', 'Antipolo, Rizal', 'EDBO Quality Assurance Office'),
('ARMM', 'Regional Office', 'Cotabato City', 'REGION XIV REGIONAL OFFICE (BARMM)'),
('ARMM', 'Maguindanao Branch', 'Cotabato City', 'MAGUINDANAO BRANCH OFFICE'),
('ARMM', 'Lanao del Sur Branch', 'Marawi City', 'LANAO DEL SUR - BRANCH OFFICE'),
('ARMM', 'BASULTA Branch', 'Isabela City', 'BASILAN-BRANCH OFFICE'),
('ARMM', 'BASULTA Branch', 'Patikul, Sulu', 'SULU SATELITE OFFICE'),
('ARMM', 'BASULTA Branch', 'Bongao', 'TAWI-TAWI SATELITE OFFICE'),
('ARMM', 'Maguindanao Branch', 'Sultan Kudarat', 'GID 6'),
('ARMM', 'Maguindanao Branch', 'Maguindanao Del Sur', 'GID SHARIFF AGUAK'),
('ARMM', 'Lanao del Sur Branch', 'Lanao Del Sur', 'GID MARAWI'),
('ARMM', 'BASULTA Branch', 'Basilan', 'GID BASILAN'),
('ARMM', 'BASULTA Branch', 'Sulu', 'GID SULU'),
('ARMM', 'BASULTA Branch', 'Tawi-Tawi', 'GID TAWI-TAWI'),
('ARMM', 'Lanao del Sur Branch', 'Marawi City', 'SHIN HEUNG RECIRCULATING GRAIN DRYER'),
('CARAGA', 'Regional Office CARAGA', 'Agusan Del Norte', 'CARAGA REGIONAL OFFICE'),
('CARAGA', 'Agusan Del Sur Branch Office', 'Agusan Del Sur', 'AGUSAN DEL SUR BRANCH OFFICE'),
('CARAGA', 'Agusan Del Sur Branch Office', 'Agusan Del Norte', 'GID LIBERTAD I WHSE.'),
('CARAGA', 'Agusan Del Sur Branch Office', 'Agusan Del Norte', 'GID LIBERTAD II WHSE.'),
('CARAGA', 'Agusan Del Sur Branch Office', 'Agusan Del Sur', 'GID BAYUGAN WHSE.'),
('CARAGA', 'Agusan Del Sur Branch Office', 'Agusan Del Sur', 'GID ALEGRIA WHSE.'),
('CARAGA', 'Agusan Del Sur Branch Office', 'Agusan Del Sur', 'GID TRENTO WHSE.'),
('CARAGA', 'Surigao Del Sur Branch Office', 'Surigao Del Sur', 'SURIGAO DEL SUR BRANCH OFFICE'),
('CARAGA', 'Surigao Del Sur Branch Office', 'Surigao Del Sur', 'GID DUPLEX WHSE'),
('CARAGA', 'Surigao Del Sur Branch Office', 'Surigao Del Sur', 'GID MANGAGOY WHSE'),
('CARAGA', 'Surigao Del Sur Branch Office', 'Surigao Del Sur', 'GID CANTILAN WHSE'),
('CARAGA', 'Surigao Del Sur Branch Office', 'Surigao Del Norte', 'GID KM. 10 WHSE'),
('CARAGA', 'Surigao Del Sur Branch Office', 'Surigao Del Norte', 'GID DAPA WHSE'),
('CARAGA', 'Surigao Del Sur Branch Office', 'Province Of Dinagat Islands', 'GID SAN JOSE WHSE');
INSERT IGNORE INTO regions (name) SELECT DISTINCT region FROM location_masterlist;
INSERT IGNORE INTO branch_offices (region_id, name)
SELECT DISTINCT r.id, l.branch FROM location_masterlist l JOIN regions r ON r.name = l.region;
INSERT IGNORE INTO province_offices (branch_id, name)
SELECT DISTINCT b.id, l.province FROM location_masterlist l JOIN regions r ON r.name = l.region JOIN branch_offices b ON b.region_id = r.id AND b.name = l.branch;
INSERT IGNORE INTO warehouse_offices (branch_id, province_id, name)
SELECT DISTINCT b.id, p.id, l.facility_name FROM location_masterlist l JOIN regions r ON r.name = l.region JOIN branch_offices b ON b.region_id = r.id AND b.name = l.branch JOIN province_offices p ON p.branch_id = b.id AND p.name = l.province;
UPDATE warehouse_offices w
JOIN branch_offices b ON b.id = w.branch_id
JOIN location_masterlist l ON l.branch = b.name AND l.facility_name = w.name
JOIN province_offices p ON p.branch_id = b.id AND p.name = l.province
SET w.province_id = p.id
WHERE w.province_id IS NULL;
